In [1]:
if True:  # indentation is always four spaces and it is important
    print('Data Science')

Data Science


In [6]:
if False:
    print('Data Science')
print('bye for now')

bye for now


In [5]:
if False:
    print('Data Science')
    print('bye for now')

In [3]:
if True:
    print('Data Science')
    print('bye for now')

Data Science
bye for now


Let us do one program as if divide by 2 then reminder is 0 then it is even number if remainder is not 0 then it is odd number

In [7]:
# to print only even number
x = 4
r =  x%2
if r == 0:
    print('Even number')

Even number


In [8]:
# to print only even number
x = 5    # it wont print any, bcoz it is not an even number and the reminder is 1
r =  x%2
if r == 0:
    print('Even number')

In [9]:
x = 5
r =  x%2
if r == 0:
    print('Even number')  # if it doesn't have an indentation at the end, then it will start from the next line
                            at very starting
print('odd number')

odd number


In [10]:
x = 5
r =  x%2
if r == 0:
    print('Even number')
    print('odd number')

In [13]:
x = 8
r = x % 2
if r == 0:
    print('Even number')
print('odd number')

Even number
odd number


In [14]:
x = 8   # in this we're using if,else condition
r = x % 2
if r == 0:
    print('Even number')
else:
    print('odd number')

Even number


In [15]:
x = 9   # in this we're using if,else condition
r = x % 2
if r == 0:
    print('Even number')
else:
    print('odd number')

odd number


In [16]:
x = 8   # we're using here as both if & if statement
r = x % 2
if r == 0:
    print('Even number')
if r == 1:
    print('odd number')

Even number


In [17]:
x = 9   
r = x % 2
if r == 0:
    print('Even number')
if r == 1:
    print('odd number')

odd number


In [18]:
x = 19
r = x % 2
if r == 0:
    print('Even Number')
if r != 0:
    print('odd number')

odd number


If we see the code, we're using too maly lines. Many of them want to reduce the code length which is very good practise. Instead, we can use if & else condition

In [19]:
x = 5
r = x % 2
if r == 0:
    print('Even number')
else:
    print('odd number')

odd number


In [20]:
x = 4
r = x % 2
if r == 0:
    print('Even number')
else:
    print('odd number')

Even number


Nested if (if we have 2 condition so we need to implement with nested if)

In [24]:
x = 3
r = x % 2
if r == 0:
    print('Even number')
    if x>5:
        print('greater number')
else:
    print('Odd number')

Odd number


In [25]:
x = 7
r = x % 2
if r == 0:
    print('Even number')
    if x>5:
        print('greater number')
else:
    print('Odd number')

Odd number


In [26]:
x = 6
r = x % 2
if r == 0:
    print('Even number')
    if x>5:
        print('greater number')
else:
    print('Odd number')

Even number
greater number


In [28]:
x = 4
r = x % 2
if r == 0:
    print('Even number')
    if x>5:
        print('greater number')
    else:
        print('not greater')
else:
    print('Odd number')

Even number
not greater


In [31]:
x = 5
r = x % 2
if r == 0:
    print('Even number')
    if x>5:
        print('greater number')
    else:
        print('not greater')
else:
    print('Odd number')

Odd number


We have more concepts like(if, elif, else)

In [34]:
#when we use 'if' it will check all condition but if we mention 'elif' then it wont check all condition
# when we use 'if' condition it will check  every block of code  better debug in pycharm
# you can debug with value 1 & d for both if & elif

x = 4
if x == 1:
    print('One')
if x == 2:
    print('Two')
if x == 3:
    print('Three')
if x == 4:
    print('Four')

Four


In [35]:
# 'elif' it wont check till the block, once you find the output it wont go to next line
# you can try with multiple parameter 1, 2 & 3 value in x 

x = 1
if(x == 1):
    print('One')
elif(x == 2):
    print('Two')
elif(x == 3):
    print('Three')
elif(x == 4):
    print('Four')

One


In [37]:
x = 7   # no output
if(x == 1):
    print('One')
elif(x == 2):
    print('Two')
elif(x == 3):
    print('Three')
elif(x == 4):
    print('Four')

In [38]:
x = 7
if(x == 1):
    print('One')
elif(x == 2):
    print('Two')
elif(x == 3):
    print('Three')
elif(x == 4):
    print('Four')
else:
    print('wrong output')

wrong output


In [39]:
x = 4
if(x == 1):
    print('One')
elif(x == 2):
    print('Two')
elif(x == 3):
    print('Three')
elif(x == 4):
    print('Four')
else:
    print('wrong output')

Four


In [40]:
# short hand if
a = 30
b = 20
if a > b:
    print('a is greater than b')

a is greater than b


In [41]:
a = 30
b = 20
if a < b:
    print('a is greater than b')

In [44]:
a = 20
b = 30
if a > b:
    print('a is greater than b')
else:
    print('a is less than b')

a is less than b


In [45]:
a = 20
b = 30
if a < b:
    print('a is greater than b')
else:
    print('a is less than b')

a is greater than b


LOOPS -- in programing world some time we keep on repeating , may be you want to repeat 5 statement so one way is copy & paste multiple times or other way is 

if you want to print the datascience 1000 times then what you will you cant copy for 1000 times , if you want to print 1000 times then you cant do manualy . that is the reason why we need to apply loop ->
2 type of loops --  While loop & For loop

In [46]:
print('data science')
print('data science')
print('data science')
print('data science')
print('data science')

data science
data science
data science
data science
data science


In [47]:
i = 1   # initializing
while i <= 5:  # condition
    print('data science')
    i = i + 1  # increment   # until the statement is satisfied, becoz it repaets with every step

data science
data science
data science
data science
data science


In [48]:
i = 5   # initializing
while i >= 1:  # condition
    print('data science')
    i = i - 1 #decrement

data science
data science
data science
data science
data science


In [49]:
i = 1   # initializing
while i <= 5:  # condition
    print('data science', i)
    i = i + 1 # increment

data science 1
data science 2
data science 3
data science 4
data science 5


In [50]:
i = 5          # initializing
while i>=1:    # condition
    print('data science',i)
    i = i - 1 #decrement

data science 5
data science 4
data science 3
data science 2
data science 1


can we use multiple while loop || nested while loop to understand nested while indepth understand you can use pycharm debug with f8 option

In [51]:
i = 1
while i<=5:
    print('data science') # when we mention end then new line will not create
    j = 1
    while j<=4:
        print('technology')
        j = j + 1
        
    i = i + 1
    print()

data science
technology
technology
technology
technology

data science
technology
technology
technology
technology

data science
technology
technology
technology
technology

data science
technology
technology
technology
technology

data science
technology
technology
technology
technology



In [52]:
i = 1
while i<=5:
    print('datascience', end = "")
    j = 1
    while j<=4:
        print('technology', end="")
        j = j+1
        
    i = i + 1
    print()

datasciencetechnologytechnologytechnologytechnology
datasciencetechnologytechnologytechnologytechnology
datasciencetechnologytechnologytechnologytechnology
datasciencetechnologytechnologytechnologytechnology
datasciencetechnologytechnologytechnologytechnology


In [53]:
# lets use while loop using some numbers
i = 1
while i <=2:
    j = 0
    while j<=2:
        print(i*j, end = "")
        j += 1
    print()
    i += 1

012
024


In [54]:
# lets use while loop using some numbers
i = 1
while i <=4:
    j = 0
    while j<=3:
        print(i*j, end = "")
        j += 1
    print()
    i += 1

0123
0246
0369
04812


FOR LOOP  -
normally while loop it work with iteration or certaion some condition but for loop it will work with sequence (list, string,int)

In [55]:
name = 'nit'
for i in name:
    print(i)

n
i
t


In [56]:
name1 = [1,3.5,'hello']  # to print the value individually
for i in name1:
    print(i)

1
3.5
hello


In [57]:
for i in [2,3,5.5,'hi']:
    print(i)

2
3
5.5
hi


In [59]:
range(5)

range(0, 5)

In [60]:
for i in range(5):
    print(i)

0
1
2
3
4


In [63]:
for i in range(2,5):
    print(i)

2
3
4


In [64]:
for i in range(1,10,3):
    print(i)

1
4
7


In [65]:
for i in range(1,21):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


In [1]:
print(i)

NameError: name 'i' is not defined

In [66]:
# print the value which is divisible by 5
for i in range(1,51):
    if i%5==0:
        print(i)

5
10
15
20
25
30
35
40
45
50


In [67]:
# print the value which is divisible by 5 and i dont want that value
for i in range(1,21):
    if i%5!=0:
        print(i)

1
2
3
4
6
7
8
9
11
12
13
14
16
17
18
19


- ABOUT 3 KEYWORDS -- BREAK || CONTINUE || PASS

  BREAK STATEMNT - if you apply break statment in a loop then it will end the loop
- Pass = skips block of code( function, class etc)
- Continue = skips 1 step/iteration during loop
- Break = jumps out of the function/loop

In [72]:
# Assume and write the code like user ask choclate from vendor machine then write the basic code 

x = int(input('How many choclates we want:?'))

i = 1
while i<=x:
    print('choclate')
    i += 1       

How many choclates we want:?5
choclate
choclate
choclate
choclate
choclate


In [73]:
x = int(input('How many choclates we want:?'))

i = 1
while i<=x:
    print('choclate')
    i += 1       

How many choclates we want:?10
choclate
choclate
choclate
choclate
choclate
choclate
choclate
choclate
choclate
choclate


- If the user says i need 100 choclet but vending machine dont have 100 choclate & machine has only 50    choclate so what you do on those scenario
- We have 3 choice now  (eiter stop the transaction by you or you can give only 50 choclate) & may be
   vendor machine display the result as we are out of the stock
- Now lets do this code 

In [75]:
avail = 5
x = int(input('How many choclates we want:?'))
i = 1
while i <= x:
    print('choclate')
    i += 1
# if you check the user wants 10 choclets  but availabe choclet is 5 but we got output as 10 choclet
# in this code we just declare but we dint apply any condition to it 

How many choclates we want:?10
choclate
choclate
choclate
choclate
choclate
choclate
choclate
choclate
choclate
choclate


In [76]:
avail_choco = 5
x = int(input('How many chocolates we want:?'))

i = 1
while i<=x:
    if i>avail_choco:  # we stop the execution but which code execution is not entire code ,i want to come out of while loop 
        break      # break is a statement | means jump out of the loop
    print('chocolate') 
    i += 1
    
print('bye for now')

How many chocolates we want:? 10
chocolate
chocolate
chocolate
chocolate
chocolate
bye for now


In [79]:
avail_choco = 5
x = int(input('How many chocolates we want:?'))

i = 1
while i<=x:
    if i>avail_choco:
        print('out of stock')
        break
    print('chocolate')
    i +=1
    
print('bye for now')

How many chocolates we want:?20
chocolate
chocolate
chocolate
chocolate
chocolate
out of stock
bye for now


In [80]:
for i in range(1,11):
    print(i)

1
2
3
4
5
6
7
8
9
10


In [81]:
for i in range(1,11):
    if i == 7:
        break
    print(i)

1
2
3
4
5
6


In [82]:
# in continue loop, wont be terminate & exclude the assign number it give you the entire output
for i in range(1,11):
    if i == 3:
        continue
    print(i)

1
2
4
5
6
7
8
9
10


In [84]:
for i in range(1,11):
    if i == 5:
        continue
    print(i)

1
2
3
4
6
7
8
9
10


In [86]:
for i in range(1,11):
    if i == 6:
        continue
    print('hello',i)

hello 1
hello 2
hello 3
hello 4
hello 5
hello 7
hello 8
hello 9
hello 10


In [87]:
#PASS Statement - pass the code & it wont go ( code give you the error)
for i in range(1,11):

SyntaxError: incomplete input (358927178.py, line 2)

In [88]:
for i in range(1,11):
    pass

you need to print the number from 1 to 50 but dont print the value which is divisible by 3 or 5 

In [89]:
for i in range(1,51):  # in this, getting the multiplication table of specified value to the mentioned range
    if i%3 == 0:
        print(i)
print('end')    

3
6
9
12
15
18
21
24
27
30
33
36
39
42
45
48
end


In [91]:
for i in range(1,51):   # in this, getting the multiplication table of specified value to the mentioned range
    if i%2 == 0:
        print(i)
print('end')    

2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
end


In [90]:
for i in range(1,51):   # in this,, it will skip all the values which is divisible by 3
    if i%3 == 0:
        continue
    print(i)
print('end')  

1
2
4
5
7
8
10
11
13
14
16
17
19
20
22
23
25
26
28
29
31
32
34
35
37
38
40
41
43
44
46
47
49
50
end


In [92]:
for i in range(1,51):  # in this, it will skip all the values which is divisible by 6
    if i%6 == 0:
        continue
    print(i)
print('end')  

1
2
3
4
5
7
8
9
10
11
13
14
15
16
17
19
20
21
22
23
25
26
27
28
29
31
32
33
34
35
37
38
39
40
41
43
44
45
46
47
49
50
end


In [93]:
for i in range(1,51):   # it will skip all the value which is divisible by 3 or 5
    if i%3 == 0 or i%5 == 0:
        continue
    print(i)
print('end') 

1
2
4
7
8
11
13
14
16
17
19
22
23
26
28
29
31
32
34
37
38
41
43
44
46
47
49
end


In [97]:
for i in range(1,50):   # when you apply "and" you wont get the value which is divisible by both 3 and 5 (15)
    if i%3 == 0 and i%5 == 0:
        continue
    print(i)
print('end')    

1
2
3
4
5
6
7
8
9
10
11
12
13
14
16
17
18
19
20
21
22
23
24
25
26
27
28
29
31
32
33
34
35
36
37
38
39
40
41
42
43
44
46
47
48
49
end


In [98]:
# we dont want to print the values which are even numbers that means print only odd numbers
for i in range(1,51):
    
    if (i%2 == 0):
        pass
    else:
        print(i)
print('bye')

1
3
5
7
9
11
13
15
17
19
21
23
25
27
29
31
33
35
37
39
41
43
45
47
49
bye


In [120]:
for i in range(0,51):
    
    if (i%2 == 1):
        pass
    else:
        print(i)
print('bye')

0
2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
bye


In [121]:
for i in range(1,51):
    
    if (i%2 == 1):
        pass
    else:
        print(i)
print('bye')

2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
bye


In [122]:
# printing pattern in python
print('# # # #')
print('# # # #')
print('# # # #')
print('# # # #')

# # # #
# # # #
# # # #
# # # #


In [123]:
for j in range(4):
    print('#')

#
#
#
#


In [124]:
for j in range(4):
    print('#', end=" ")
for j in range(4):
    print('#', end=" ")

# # # # # # # # 

In [126]:
for j in range(4):
    print('#', end=" ")
print()
for j in range(4):
    print('#', end=" ")

# # # # 
# # # # 

In [127]:
for j in range(4):
    print('#', end=" ")
print()
for j in range(4):
    print('#', end=" ")
print()
for j in range(4):
    print('#', end=" ")
print()
for j in range(4):
    print('#', end=" ")

# # # # 
# # # # 
# # # # 
# # # # 

In [128]:
# instead of using that big code, we use this short code to get the same output
for i in range(4):
    for j in range(4):
        print('#',end=" ")
    print()

# # # # 
# # # # 
# # # # 
# # # # 


In [129]:
list(range(5))

[0, 1, 2, 3, 4]

In [130]:
for i in range(4):
    for j in range(i):
        print('#',end=" ")
    print()


# 
# # 
# # # 


In [132]:
for i in range(4):
    for j in range(i+1):
        print('#',end=" ")
    print()

# 
# # 
# # # 
# # # # 


In [133]:
for i in range(4):
    for j in range(4-i):
        print('#', end=" ")
    print()

# # # # 
# # # 
# # 
# 


For | Else in python
- In other language for else not supportable but in python it is supportable

eg- lets print the number from 1- 20 & we dont want to print number which is divisible by 5

In [134]:
nums = [12,15,18,21,26]
for num in nums:
    if num % 5 == 0:
        print(num)

15


In [135]:
nums = [12,14,18,21,25,30,35]
for num in nums:
    if num % 5 == 0:
        print(num)

25
30
35


In [136]:
nums = [12,14,18,21,25,20]
for num in nums:
    if num % 5 == 0:
        print(num)  

25
20


In [137]:
nums = [12,14,18,21,25,20]  # output will be the very first no. from the list which is divisible by 5. 
                            it will print only 1 number which appears a first in the list, then it break
for num in nums:
    if num % 5 == 0:
        print(num)  
        break

25


In [138]:
nums = [12,14,18,21,20,25]
for num in nums:
    if num % 5 == 0:
        print(num)  
        break

20


In [139]:
nums = [10,14,18,21,5,10]
for num in nums:
    if num % 5 == 0:
        print(num)  
        break

10


In [140]:
nums = [7,14,18,21,23,27] #see there is no number which is divisible by 5 we got output as blank
for num in nums:
    if num % 5 == 0:
        print(num)  
        break

In [141]:
nums = [7,14,18,21,23,27] # check every iteration until all the conditions checked
for num in nums:
    if num % 5 == 0:
        print(num)  
        break
    else:
        print('Number Not Found')

Number Not Found
Number Not Found
Number Not Found
Number Not Found
Number Not Found
Number Not Found


In [142]:
nums = [7,14] 
for num in nums:
    if num % 5 == 0:
        print(num)  
        break
    else:
        print('Number Not Found')

Number Not Found
Number Not Found


In [143]:
nums = [7,14,18,21,23,27] 
for num in nums:
    if num % 5 == 0:
        print(num)  
        break
else:
        print('Number Not Found')

Number Not Found


In [144]:
nums = [10,14,18,21,20,27]  #  "#break" makes a differnce
for num in nums:
    if num % 5 == 0:
        print(num)  
        #break
else:
        print('Not Found')

10
20
Not Found


In [147]:
nums = [10,14,18,21,20,27,30] 
for num in nums:
    if num % 5 == 0:
        print(num)  
        #break
else:
        print('Not Found')

10
20
30
Not Found


In [148]:
nums = [10,14,18,21,20,27,30] 
for num in nums:
    if num % 5 == 0:
        print(num)  
        break
else:
        print('Not Found')

10


In [150]:
# prime number - how to check given number is prime number or not
num = 12
for i in range(2,num):
    if num % i == 0:
        print('Not a Prime Number')
        break
else:
    print('Prime Number')

Not a Prime Number


In [151]:
num = 13
for i in range(2,num):
    if num % i == 0:
        print('Not a Prime Number')
        break
else:
    print('Prime Number')

Prime Number


In [152]:
num = 19
for i in range(2,num):
    if num % i == 0:
        print('Not a Prime Number')
        break
else:
    print('Prime Number')

Prime Number


In [153]:
from array import *
arr = array('i',[])
n = int(input('enter the length of the array'))

for i in range(5):
    x = int(input('Enter the next value'))
    arr.append(x)
print(arr)

enter the length of the array2
Enter the next value5
Enter the next value3
Enter the next value4
Enter the next value2
Enter the next value1
array('i', [5, 3, 4, 2, 1])


In [154]:
from numpy import *
arr = array([1,2,3,4,5])
print(arr)
type(arr)

[1 2 3 4 5]


numpy.ndarray

In [156]:
print(arr.dtype)

int32


In [157]:
arr = array([1,2,3,4,5.9])
print(arr)

[1.  2.  3.  4.  5.9]


In [158]:
print(arr.dtype)

float64


In [159]:
arr2 = array([1,2,3,4,5.9],float)
arr2

array([1. , 2. , 3. , 4. , 5.9])

In [160]:
arr3 = array([1,2,3,4,5.6],int)
arr3

array([1, 2, 3, 4, 5])

In [161]:
import numpy as np

In [163]:
arr4 = np.linspace(0,16,10) 
# break the code between 10 spaces between 0 to 16 but why decimal becuase we break into parts thats why it is floats
arr4

array([ 0.        ,  1.77777778,  3.55555556,  5.33333333,  7.11111111,
        8.88888889, 10.66666667, 12.44444444, 14.22222222, 16.        ])

In [164]:
arr5 = np.arange(0,10,2)
arr5

array([0, 2, 4, 6, 8])

In [165]:
arr6 = np.zeros(5)
arr6

array([0., 0., 0., 0., 0.])

In [166]:
arr7 = np.ones(5)
arr7

array([1., 1., 1., 1., 1.])